packages:
  - '.'
overridePackages:
  sharp: '^0.33.5'
allowBuilds:
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
patchedDependencies:
  client-only@0.0.1: patches/client-only@0.0.1.patch
